language: r
cache: packages
sudo: required
install:
  - R -e 'install.packages("devtools", repos = "http://cran.rstudio.com")'
  - R -e 'devtools::install_deps(dep = TRUE)'
script:
  - R CMD build .
  - R CMD check *tar.gz
