---
title: "How to publish headlines"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{How to publish headlines}
  %\VignetteEncoding{UTF-8}
  %\VignetteEngine{knitr::rmarkdown}
editor_options: 
  chunk_output_type: console
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

## Headlines as a list

Here's how to publish RSS data from [sciencegeist.com](https://www.sciencegeist.ch) as a list of headlines.

```{r, eval=FALSE}
library(headliner)
library(dplyr)
data(sciencegeist)

sciencegeist %>% 
  head(10) %>%
  headlines(title = "Sciencegeist newsfeed",
            save_as = "headlines.html")
```

Please note: images are not shown in this layout.

## Headlines as thumbnails

```{r, eval=FALSE}
sciencegeist %>% 
  head(10) %>%
  headlines(title = "Sciencegeist newsfeed", 
            save_as = "headlines.html",
            layout = "card")
```

`headliner` also offers a PDF printout possibility.

```{r, eval=FALSE}
sciencegeist %>% 
  head(10) %>% # 21 gives two erros: &amp; in title and .gif
  headlines(title = "Sciencegeist newsfeed", 
            save_as = "headlines.pdf")
```

