---
params:
  main_title: NULL
  headlines: NULL
  block_type: NULL
---

---
title: `r purrr::pluck(params, "main_title")`
output: 
  html_document:
    theme: simplex
---

---

```{r, echo=FALSE, results='asis'}

# ---- add defaults to possibly missing data
df <- purrr::pluck(params, "headlines")

if (!"pubDate" %in% colnames(df))
  df <- dplyr::mutate(df, pubDate = "")

if (!"description" %in% colnames(df))
  df <- dplyr::mutate(df, description = "")

if (!"link" %in% colnames(df))
  df <- dplyr::mutate(df, link = "#")

# default: list layout style
md <- ""
fn_block <- system.file(
  "rmd", "templates", "list_element.Rmd", package = "headliner")

# modify default if card layout type
if (purrr::pluck(params, "block_type") == "card") {
  md <- c(md,
          "<style>.row.display-flex{display:flex;flex-wrap:wrap}.thumbnail{height:95%}.thumbnail{display:flex;flex-direction:column}</style>", 
          "")
  fn_block <- system.file(
    "rmd", "templates", "card_element.html", package = "headliner")
}

# ---- write and knit data.frame
md <- c(md, purrr::pmap_chr(df, knitr::knit_expand, fn_block))

knitr::knit(text = md, quiet = TRUE) %>% 
  glue::glue_collapse("\n")
```

```{r debug, eval=FALSE, include=FALSE}
print(fn_block)
print(head(df))
print(md)
```

